### ISSUE TITLE
DevKit SDK 2.0.0 Release Candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [microsoft/devkit-sdk#1016]
This is a big milestone for IoT DevKit to support the new IoT Plug and Play.

- [ ] #1015 Support Plug & Play.
- [ ] #1012 Run set_az_iothub, the device connection string is truncated if it's length > 128. 
- [ ] #1010 Don't load device connection string from EEPROM when reconnect to IoTHub
