### ISSUE TITLE
DevKit SDK 1.3.3 release candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#762]
Feature:
- [x] #755 Expose WebSocket (not include SSL)
- [x] #754  [DPS] The device enrollment tool for macOS
- [x] #675 Enable mbed_memory_status function 

Bug fixing:
- [x] #758 error: NAU88C10.h: No such file or directory  #include "NAU88C10.h"
- [x] #757 error: Riot.h: No such file or directory #include "Riot.h"
- [x] #750 Fix the doubleFree issue reported by CppCheck
- [x] #752 Error infomation contains build machine's path information 
- [x] #764 Security: Use of strncopy() function in "Get Started" project 

Mini-solution:
- [x] #727 Add Remote Monitoring V2

Special thanks to [Alexandre Dumont](https://github.com/adumont), [Juan Manuel Servera Bondroit](https://github.com/jmservera) , [Chris Lovett](https://github.com/lovettchris), [Prafull Kotecha](https://github.com/prafullkotecha), thank you for your contributions and feedbacks.
