### ISSUE TITLE
DevKit SDK 1.3.5 Release Candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#801]
- [x] #802 Update IoT Hub installer such that it works for users who only have resource group-level access 
- [x] #799 MQTTNetwork TCPSocket issue 
- [x] #796 [GDPR] Do not send project name in plain text 
- [x] #789 Support interrupts functions 
- [x] #767 Filter out DevKit hotspot in the WiFi configuration page 
- [x] #673 Support watchdog timer 
- [x] #807 Task 'cloud-provision' failed due to imcompatible azure cli 
- [x] #792 Figure out DevKit + IoT Edge solutions
