### ISSUE TITLE
DevKit SDK 1.3.7 Release Candidates

### ISSUE THREAD

**Issue by ihere1** [Microsoft/devkit-sdk#819]
- [x] #785 Display more useful info for default firmware
- [x] #821 Memory usage API bug fix
- [x] #828 Add sleep mode for power saving 
- [x] #831 Add HTTPClient document
- [x] #832 Remove sdk dependency from installation script 
- [x] #834 [User Feedback] Improve error message for serial port access denied
- [x] #839 The size of .bin file increased a lot after enable DPS

**Comment by ArthurMa1978** [comment]
Due to some underlying RTX issue, we have to postpone this release.
