### ISSUE TITLE
DevKit SDK 1.4.0 Release Candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#840]
- [x] #850 Deprecate existing installation package
- [x] #830 Add firmware update support in bootloader
- [x] #835 The rule of temperatureAlert is wrong 
- [x] #857 Enable change the audio volume
- [x] #854 Update mini solution of Devkit Translator
