### ISSUE TITLE
DevKit SDK 1.4.1 Release Candidates

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#875]
- [x] #879 Add OTA mini-solution 
- [x] #858 Added support for using pins 1 and 2 as Serial1
- [x] #863 useless comparisons 
- [x] #883 Enable Automatic Level Control on microphone.
