### ISSUE TITLE
DevKit SDK 1.5.1 Release Candidates 

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#908]
- [x] #907 Update Azure IoT SDK to latest to support DPS group enrollment
- [x] #906 Memory leak from GetHostNameFromConnectionString
- [x] #910 The SystemTickCounterRead is not thread safety
- [x] #901 Fix the file system example
