### ISSUE TITLE
DevKit SDK 1.6.2 Release Candidates 

### ISSUE THREAD

**Issue by ArthurMa1978** [Microsoft/devkit-sdk#974]
- [x]  #957 Fix memory leak in /AZ3166/src/libraries/WiFi/src/AZ3166WiFiUdp.cpp
- [x]  #956 Support customized time server 
- [x]  #975 Fix the unittest failure due to 'HEX' definition change 
- [x]  #976 Improve the DevKitMQTTClient to handle bad network enviroment 
- [x] #977 Fix build warnings
- [x] #978 Upgrade Azure IoT C SDK to 1.2.14
- [x] #979 Support un-sorted server cert chain during TLS handshake
- [x] #983 Remove the user info in the error info
- [x] #1001 Support customized WebServer for system configuration
